import { voucherStatus, fileStatus } from 'src/models/money/voucher/constants';
import React from 'react';

export default {
  detailColumns: [
    {
      title: '序号',
      dataIndex: 'orderNo',
      width: 50,
      fixed: 'left',
    }, {
      title: '凭证编号',
      dataIndex: 'no',
      width: 100,
      fixed: 'left',
    }, {
      title: '汇率类型',
      dataIndex: '',
    }, {
      title: '凭证类型',
      dataIndex: '',
    }, {
      title: '账套',
      dataIndex: 'accountBook',
    }, {
      title: '公司段',
      dataIndex: 'companySection',
    }, {
      title: '业务段',
      dataIndex: 'businessSegment',
    }, {
      title: '成本中心段',
      dataIndex: 'costCenterSection',
    }, {
      title: '产品段',
      dataIndex: 'productSegment',
    }, {
      title: '科目段',
      dataIndex: 'subjectSection',
    }, {
      title: '科目名称',
      dataIndex: 'subject',
    }, {
      title: '子目段',
      dataIndex: 'subSection',
    }, {
      title: '子目段',
      dataIndex: '',
    }, {
      title: '备用段1',
      dataIndex: 'sparePart1',
    }, {
      title: '关联方(备用2)',
      dataIndex: 'sparePart2',
    }, {
      title: '借方额',
      dataIndex: 'debit',
    }, {
      title: '贷方额',
      dataIndex: 'credit',
    }, {
      title: '凭证批名',
      dataIndex: 'batchName',
    }, {
      title: '批次描述',
      dataIndex: 'batchDesc',
    }, {
      title: '凭证名',
      dataIndex: 'voucherName',
    }, {
      title: '凭证描述',
      dataIndex: 'voucherDesc',
    }, {
      title: '凭证行描述',
      dataIndex: 'voucherLineDesc',
    }, {
      title: '弹性域1',
      dataIndex: 'attribute1',
    }, {
      title: '弹性域2',
      dataIndex: 'attribute2',
    }, {
      title: '弹性域3',
      dataIndex: 'attribute3',
    }, {
      title: '弹性域4',
      dataIndex: 'attribute4',
    }, {
      title: '弹性域5',
      dataIndex: 'attribute5',
    }, {
      title: '弹性域6',
      dataIndex: 'attribute6',
    }, {
      title: '弹性域7',
      dataIndex: 'attribute7',
    }, {
      title: '弹性域8',
      dataIndex: 'attribute8',
    }, {
      title: '弹性域9',
      dataIndex: 'attribute9',
    }, {
      title: '弹性域10',
      dataIndex: 'attribute10',
    }, {
      title: '系统名称',
      dataIndex: 'systemName',
    }, {
      title: '产品名称',
      dataIndex: 'productName',
    }, {
      title: '发票编号',
      dataIndex: 'invoiceNo',
    }, {
      title: '凭证文件生成日期',
      dataIndex: 'sendDate',
    }, {
      title: '凭证文件状态',
      dataIndex: 'fileStatus',
      fixed: 'right',
      render: value => fileStatus[value] || '',
    }, {
      title: '制证状态',
      dataIndex: 'voucherStatus',
      width: 80,
      fixed: 'right',
      render: value => voucherStatus[value] || '',
    },
  ],
};
